
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: ps-rule-assert@2
    displayName: Analyze Azure template files
    inputs:
      modules: 'PSRule.Rules.Azure'
      outputFormat: Sarif
      outputPath: reports/ps-rule-results.sarif
      inputPath: src/
      options: '/.psrule/ps-rule.yaml'

  # TO be analysed by https://marketplace.visualstudio.com/items?itemName=sariftools.scans
  - task: PublishBuildArtifacts@1
    displayName: Publish PSRule results
    inputs:
      PathtoPublish: 'reports'
      ArtifactName: 'CodeAnalysisLogs'