
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

  # Execute run-azure-psrule.ps1 script directly to generate SARIF output
  - task: PowerShell@2
    displayName: Analyze Azure template files with PSRule
    continueOnError: true
    inputs:
      filePath: '.psrule/run-azure-psrule.ps1'
      arguments: >-
        -WorkspaceDirectory $(Build.SourcesDirectory)
        -SourcePath src/vm-simple-windows
        -OutputPath reports
        -OutputFormat Sarif
      pwsh: true


  # TO be analysed by https://marketplace.visualstudio.com/items?itemName=sariftools.scans
  - task: PublishBuildArtifacts@1
    displayName: Publish PSRule results
    inputs:
      PathtoPublish: 'reports'
      ArtifactName: 'CodeAnalysisLogs'